const FACTS_ABOUT_ME = [
    "I played volleyball in high school and volleyball intramurals at school",
    "If I were a vegetable, I think I'd be a carrot because I think I'm reliable.",
    "2 of my fingernails have fallen off after closing doors on then (2 separate occasions and they grew back normally)",
    "I once hit a pillar while trying to park in a mall parking lot.",
    "I enjoy true crime podcast/documentaries.",
    "When I was younger the bear from Toy Story 3 terrified me and I had nightmares about the trash disposal scene.",
    "Something on my bucket list is to go on one of those hikes that are multiple days long (Machu Pichu at the moment).",
    "I was born at 7:30 am.",
    "As a child, I wanted to be florist, then a pharmacist. But here I am now.",
    "I was born with an extra tooth (it got pulled out so now I have the regular amount of teeth)",
    "Some hobbies I've picked up over the last few years are guitar, embroidery, and going to the gym.",
    "I worked at McDonald's when I was 16 and now I hate eating McDonalds.",
    "I think aliens are real.",
    "One snack that I avoid buying is granola because I will eat it straight out of the box.",
    "My favourite chip flavour is Miss Vickies Jalapeno Chips",
    "My favourite song is Drops of Jupiter by Train",
    "I like the smell of paint",
    "The last book that made me cry was The Kite Runner",
    "I hate sleeping with socks on.",
    "In 2022, I listened to 73,530 minutes on Spotify, more than 96% other listeners in Canada.", 
    "In 2022, my top Spotify Wrapped song was Cleopatra by the Lumineers.",
    "In 2022, my second top Spotify Wrapped song was champagne problems by Taylor Swift.",
    "In 2022, my third top Spotify Wrapped song was The Most Beautiful Thing by Bruno Major.",
    "In 2022, my fourth top Spotify Wrapped song was Cherry Wine by Hozier.",
    "In 2022, my fifth top Spotify Wrapped song was All Too Well (10 Minute Version) (Taylor's Version) by Taylor Swift.",
    "Cats > dogs",
    "I love getting hired! (pls hire me)",
]

export default FACTS_ABOUT_ME