const FACTS_ABOUT_ME = [
    "I played volleyball in high school and volleyball intramurals at school",
    "If I were a vegetable, I think I'd be a carrot because I think I'm reliable.",
    "My star sign is Aries but I don't think I'm hotheaded at all.",
    "2 of my fingernails have fallen off after closing doors on then (2 separate occasions and they grew back normally)",
    "I'd say I'm an alright driver but I can't park. I once a pillar while trying to park in a mall parking lot.",
    "I enjoy true crime podcast/documentaries.",
    "When I was younger the bear from Toy Story 3 terrified me and I had nightmares about the trash disposal scene.",
    "Something on my bucket list is to go on one of those hikes that are multiple days long (Machu Pichu at the moment).",
    "I was born at 7:30 am.",
    "As a child, I wanted to be florist, then a pharmacist. But here I am now.",
    "I was born with an extra tooth (it got pulled out so now I have the regular amount of teeth)",
    "I'm Vietnamese but I think pho is overrated",
    "Some hobbies I've picked up over the last few years are guitar, embroidery, and going to the gym.",
    "I worked at McDonald's when I was 16 and now I hate eating McDonalds.",
    "I think aliens are real.",
    "I actually like black licorice because when I was younger, my piano teacher gave out candy at the end of each lessons and she would give me 2 candies if I took the black licorice jujube.",
    "One snack that I avoid buying is granola because I will eat it straight out of the box.",
    "My favourite chip flavour is Miss Vickies Jalapeno Chips",
    "My favourite song is Drops of Jupiter by Train",
    "I like houseplants, I have a snake plant, a money tree, and 4 cacti/succulents.",
    "I've lived in Ottawa my whole life and the best thing about it is the shawarma.",
    "I like to use ellipses and emojis while messaging (even on Slack) because I think conveys my message better.",
    "I like the smell of paint but can't stand the smell of boiled eggs",
    "The last book that made me cry was The Kite Runner",
    "My Hogwarts house is Ravenclaw abut sometimes I think I might be Slytherin.",
    "I've been to Europe and North America",
    "My favourite color is green. Like an emerald green",
    "I hate sleeping with socks on.",
    "I have never pulled an all nighter in my life and I think if I would rather just fail than not sleep.",
    "I am testing this game and now just realizing these facts are terrible...sorry."

]

export default FACTS_ABOUT_ME